const axios = require('axios');

const zones = {
  // Afrique
  "algérie": "Africa/Algiers",
  "angola": "Africa/Luanda",
  "bénin": "Africa/Porto-Novo",
  "botswana": "Africa/Gaborone",
  "burkina faso": "Africa/Ouagadougou",
  "burundi": "Africa/Bujumbura",
  "cameroun": "Africa/Douala",
  "cap-vert": "Atlantic/Cape_Verde",
  "comores": "Indian/Comoro",
  "congo": "Africa/Brazzaville",
  "république démocratique du congo": "Africa/Kinshasa",
  "côte d’ivoire": "Africa/Abidjan",
  "djibouti": "Africa/Djibouti",
  "égypte": "Africa/Cairo",
  "érythrée": "Africa/Asmara",
  "eswatini": "Africa/Mbabane",
  "éthiopie": "Africa/Addis_Ababa",
  "gabon": "Africa/Libreville",
  "gambie": "Africa/Banjul",
  "ghana": "Africa/Accra",
  "guinée": "Africa/Conakry",
  "guinée-bissau": "Africa/Bissau",
  "guinée équatoriale": "Africa/Malabo",
  "kenya": "Africa/Nairobi",
  "lesotho": "Africa/Maseru",
  "libéria": "Africa/Monrovia",
  "libye": "Africa/Tripoli",
  "madagascar": "Indian/Antananarivo",
  "malawi": "Africa/Blantyre",
  "mali": "Africa/Bamako",
  "maroc": "Africa/Casablanca",
  "maurice": "Indian/Mauritius",
  "mauritanie": "Africa/Nouakchott",
  "mozambique": "Africa/Maputo",
  "namibie": "Africa/Windhoek",
  "niger": "Africa/Niamey",
  "nigéria": "Africa/Lagos",
  "ouganda": "Africa/Kampala",
  "rwanda": "Africa/Kigali",
  "sao tomé-et-principe": "Africa/Sao_Tome",
  "sénégal": "Africa/Dakar",
  "seychelles": "Indian/Mahe",
  "sierra leone": "Africa/Freetown",
  "somalie": "Africa/Mogadishu",
  "soudan": "Africa/Khartoum",
  "soudan du sud": "Africa/Juba",
  "tanzanie": "Africa/Dar_es_Salaam",
  "tchad": "Africa/Ndjamena",
  "togo": "Africa/Lome",
  "tunisie": "Africa/Tunis",
  "zambie": "Africa/Lusaka",
  "zimbabwe": "Africa/Harare",
  // Asie
  "afghanistan": "Asia/Kabul",
  "arabie saoudite": "Asia/Riyadh",
  "arménie": "Asia/Yerevan",
  "azerbaïdjan": "Asia/Baku",
  "bahreïn": "Asia/Bahrain",
  "bangladesh": "Asia/Dhaka",
  "birmanie": "Asia/Yangon",
  "brunei": "Asia/Brunei",
  "cambodge": "Asia/Phnom_Penh",
  "chine": "Asia/Shanghai",
  "corée du sud": "Asia/Seoul",
  "corée du nord": "Asia/Pyongyang",
  "émirats arabes unis": "Asia/Dubai",
  "géorgie": "Asia/Tbilisi",
  "inde": "Asia/Kolkata",
  "indonésie": "Asia/Jakarta",
  "iran": "Asia/Tehran",
  "iraq": "Asia/Baghdad",
  "israël": "Asia/Jerusalem",
  "japon": "Asia/Tokyo",
  "jordanie": "Asia/Amman",
  "kazakhstan": "Asia/Almaty",
  "kirghizistan": "Asia/Bishkek",
  "koweït": "Asia/Kuwait",
  "laos": "Asia/Vientiane",
  "liban": "Asia/Beirut",
  "malaisie": "Asia/Kuala_Lumpur",
  "maldives": "Indian/Maldives",
  "mongolie": "Asia/Ulaanbaatar",
  "népal": "Asia/Kathmandu",
  "oman": "Asia/Muscat",
  "ouzbékistan": "Asia/Tashkent",
  "pakistan": "Asia/Karachi",
  "philippines": "Asia/Manila",
  "qatar": "Asia/Qatar",
  "singapour": "Asia/Singapore",
  "sri lanka": "Asia/Colombo",
  "syrie": "Asia/Damascus",
  "taïwan": "Asia/Taipei",
  "tadjikistan": "Asia/Dushanbe",
  "thaïlande": "Asia/Bangkok",
  "timor oriental": "Asia/Dili",
  "turkménistan": "Asia/Ashgabat",
  "turquie": "Europe/Istanbul",
  "viet nam": "Asia/Ho_Chi_Minh",
  "yémen": "Asia/Aden",
  // Europe
  "allemagne": "Europe/Berlin",
  "andorre": "Europe/Andorra",
  "autriche": "Europe/Vienna",
  "belgique": "Europe/Brussels",
  "biélorussie": "Europe/Minsk",
  "bosnie-herzégovine": "Europe/Sarajevo",
  "bulgarie": "Europe/Sofia",
  "croatie": "Europe/Zagreb",
  "danemark": "Europe/Copenhagen",
  "espagne": "Europe/Madrid",
  "estonie": "Europe/Tallinn",
  "finlande": "Europe/Helsinki",
  "france": "Europe/Paris",
  "grèce": "Europe/Athens",
  "hongrie": "Europe/Budapest",
  "irlande": "Europe/Dublin",
  "islande": "Atlantic/Reykjavik",
  "italie": "Europe/Rome",
  "lettonie": "Europe/Riga",
  "liechtenstein": "Europe/Vaduz",
  "lituanie": "Europe/Vilnius",
  "luxembourg": "Europe/Luxembourg",
  "macédoine du nord": "Europe/Skopje",
  "malte": "Europe/Malta",
  "moldavie": "Europe/Chisinau",
  "monaco": "Europe/Monaco",
  "monténégro": "Europe/Podgorica",
  "norvège": "Europe/Oslo",
  "pays-bas": "Europe/Amsterdam",
  "pologne": "Europe/Warsaw",
  "portugal": "Europe/Lisbon",
  "roumanie": "Europe/Bucharest",
  "royaume-uni": "Europe/London",
  "russie": "Europe/Moscow",
  "saint-marin": "Europe/San_Marino",
  "serbie": "Europe/Belgrade",
  "slovaquie": "Europe/Bratislava",
  "slovénie": "Europe/Ljubljana",
  "suède": "Europe/Stockholm",
  "suisse": "Europe/Zurich",
  "tchéquie": "Europe/Prague",
  "ukraine": "Europe/Kiev",
  "vatican": "Europe/Vatican",
  // Amérique du Nord
  "canada": "America/Toronto",
  "états-unis": "America/New_York",
  "mexique": "America/Mexico_City",
  "guatemala": "America/Guatemala",
  "belize": "America/Belize",
  "costa rica": "America/Costa_Rica",
  "panama": "America/Panama",
  // Amérique du Sud / Latine
  "argentine": "America/Argentina/Buenos_Aires",
  "brésil": "America/Sao_Paulo",
  "chili": "America/Santiago",
  "colombie": "America/Bogota",
  "équateur": "America/Guayaquil",
  "pérou": "America/Lima",
  "uruguay": "America/Montevideo",
  "paraguay": "America/Asuncion",
  "bolivie": "America/La_Paz",
  "venezuela": "America/Caracas",
  "suriname": "America/Paramaribo",
  // Caraïbes
  "cuba": "America/Havana",
  "république dominicaine": "America/Santo_Domingo",
  "haïti": "America/Port-au-Prince",
  "jamaïque": "America/Jamaica",
  "trinité-et-tobago": "America/Port_of_Spain",
  // Océanie
  "australie": "Australia/Sydney",
  "fidji": "Pacific/Fiji",
  "kiribati": "Pacific/Tarawa",
  "marshall": "Pacific/Majuro",
  "micronésie": "Pacific/Pohnpei",
  "nauru": "Pacific/Nauru",
  "nouvelle-zélande": "Pacific/Auckland",
  "palaos": "Pacific/Palau",
  "papouasie-nouvelle-guinée": "Pacific/Port_Moresby",
  "salomon": "Pacific/Guadalcanal",
  "samoa": "Pacific/Apia",
  "tonga": "Pacific/Tongatapu",
  "tuvalu": "Pacific/Funafuti",
  "vanuatu": "Pacific/Efate"
};

module.exports = {
  config: {
    name: "heure",
    version: "2.0",
    author: "Axiomatik",
    role: 0,
    shortDescription: "Heure locale par pays (tous continents)",
    longDescription: "Affiche l'heure actuelle pour la plupart des pays du monde en français.",
    category: "utilitaire",
    guide: "{p}heure [pays]"
  },

  onStart: async function({ api, event, args }) {
    if (!args[0]) return api.sendMessage("Précise un pays. Exemple : /heure Brésil", event.threadID, event.messageID);
    const place = args.join(' ').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, "");
    const entries = Object.entries(zones);
    // Recherche tolérante, accents supprimés côté user et clé
    const zoneKey = entries.find(([k]) =>
      place.includes(k.normalize('NFD').replace(/[\u0300-\u036f]/g, ""))
    );
    if (!zoneKey) return api.sendMessage("Pays non supporté ou non reconnu.", event.threadID, event.messageID);

    try {
      const url = `https://timeapi.io/api/Time/current/zone?timeZone=${zoneKey[1]}`;
      const res = await axios.get(url);
      const heure = res.data.time;
      api.sendMessage(`Il est ${heure} en ${zoneKey[0][0].toUpperCase() + zoneKey[0].slice(1)} (${zoneKey[1]}).`, event.threadID, event.messageID);
    } catch (e) {
      api.sendMessage("Erreur d'accès à l'API TimeAPI.io.", event.threadID, event.messageID);
    }
  }
};
